USE database;

SELECT COUNT(*) AS count, CITY
FROM customers
GROUP BY CITY
HAVING COUNT(*) > 10
ORDER BY count DESC
LIMIT 100;

SELECT COUNT(*) AS count, customer_type
FROM customers
GROUP BY customer_type
ORDER BY count DESC;

SELECT *
FROM schedule_bookings
WHERE original_booked_time LIKE "%2023-09%"
LIMIT 10;

SELECT *
FROM general_log
ORDER BY postdate DESC
LIMIT 10;

SELECT *
FROM staff_pin_entry_log
LIMIT 10;

SELECT * FROM CHECKINS;

SELECT Checkins.CUSTOMER_ID, COUNT(CHECKINS.POSTDATE) as NUMBER_OF_ENTRIES, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME
FROM checkins
JOIN CUSTOMERS ON CUSTOMERS.CUSTOMER_ID=CHECKINS.CUSTOMER_ID
GROUP BY Checkins.CUSTOMER_ID
ORDER BY LASTNAME;
